/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Station {
  id: string;
  name: string;
  code: string;
  scheduledTime: string;
  actualTime?: string;
  status?: 'On Time' | 'Delayed' | 'Early';
  bay?: string;
  distance?: string;
}

export interface Bus {
  id: string;
  number: string;
  type: string;
  operator: string;
  origin: string;
  destination: string;
  startTime: string;
  endTime: string;
  duration: string;
  price: number;
  seatsLeft: number;
  status: string;
  liveTracking: boolean;
  route: [number, number][]; // Lat, Lng
  stations: Station[];
  currentSpeed?: number;
  distanceLeft?: number;
  remainingTime?: string;
  nextStop?: string;
}

export const MOCK_STATIONS: Station[] = [
  { id: '1', name: 'Bidar', code: 'BDR', scheduledTime: '09:30 AM', status: 'On Time' },
  { id: '2', name: 'Humnabad', code: 'HMN', scheduledTime: '10:15 AM', actualTime: '10:27 AM', status: 'Delayed', bay: '2', distance: '52 km' },
  { id: '3', name: 'Kalaburagi', code: 'KLBG', scheduledTime: '11:30 AM', status: 'On Time', distance: '118 km' },
];

export const MOCK_BUSES: Bus[] = [
  {
    id: '1',
    number: '07043',
    type: 'KKRTC Express',
    operator: 'KKRTC',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '6:00 AM',
    endTime: '11:30 AM',
    duration: '5h 30m',
    price: 320,
    seatsLeft: 12,
    status: 'On Time',
    liveTracking: true,
    route: [
      [17.9121, 77.5198], // Bidar
      [17.7719, 77.1293], // Humnabad
      [17.3297, 76.8343]  // Kalaburagi
    ],
    stations: MOCK_STATIONS,
    currentSpeed: 65,
    distanceLeft: 66,
    remainingTime: '1h 15m',
    nextStop: 'Dharwad Bypass Junction'
  },
  {
    id: 'local-1',
    number: 'BID-CITY-01',
    type: 'Bidar City Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'New Bus Stand',
    destination: 'Bidar Railway Station',
    startTime: '8:00 AM',
    endTime: '8:45 AM',
    duration: '45m',
    price: 20,
    seatsLeft: 30,
    status: 'Running',
    liveTracking: true,
    route: [
      [17.9121, 77.5198], // New Bus Stand
      [17.9150, 77.5250], // Ambedkar Circle
      [17.9200, 77.5300], // Shah Gunj
      [17.9250, 77.5350], // Bidar Station
    ],
    stations: [
      { id: 'l1', name: 'New Bus Stand', code: 'NBS', scheduledTime: '08:00 AM', status: 'On Time' },
      { id: 'l2', name: 'Ambedkar Circle', code: 'AC', scheduledTime: '08:15 AM', status: 'On Time' },
      { id: 'l3', name: 'Shah Gunj', code: 'SG', scheduledTime: '08:30 AM', status: 'On Time' },
      { id: 'l4', name: 'Bidar Railway Station', code: 'BRS', scheduledTime: '08:45 AM', status: 'On Time' },
    ],
    currentSpeed: 30,
    distanceLeft: 5,
    remainingTime: '15m',
    nextStop: 'Ambedkar Circle'
  },
  {
    id: 'reg-1',
    number: 'BDR-HYD-L-01',
    type: 'KSRTC Palle-Velugu',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '5:30 AM',
    endTime: '9:30 AM',
    duration: '4h 00m',
    price: 180,
    seatsLeft: 45,
    status: 'Scheduled',
    liveTracking: true,
    route: [
      [17.9121, 77.5198], // Bidar
      [17.6533, 77.7289], // Zaheerabad
      [17.5501, 78.1001], // Sangareddy
      [17.3850, 78.4867]  // Hyderabad
    ],
    stations: [
      { id: 's1', name: 'Bidar', code: 'BDR', scheduledTime: '05:30 AM', status: 'On Time' },
      { id: 's2', name: 'Zaheerabad', code: 'ZHB', scheduledTime: '06:30 AM', status: 'On Time' },
      { id: 's3', name: 'Sangareddy', code: 'SRD', scheduledTime: '08:00 AM', status: 'On Time' },
      { id: 's4', name: 'Hyderabad MGBS', code: 'HYD', scheduledTime: '09:30 AM', status: 'On Time' },
    ],
    currentSpeed: 55,
    distanceLeft: 120,
    remainingTime: '3h 00m',
    nextStop: 'Zaheerabad'
  },
  {
    id: 'local-2',
    number: 'BID-AUR-02',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar Central Bus Stand',
    destination: 'Aurad (B)',
    startTime: '10:00 AM',
    endTime: '11:45 AM',
    duration: '1h 45m',
    price: 65,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [
      [17.9121, 77.5198], // Bidar
      [18.0500, 77.5300], // Janwada
      [18.2500, 77.4300], // Aurad
    ],
    stations: [
      { id: 'a1', name: 'Bidar CBS', code: 'BCBS', scheduledTime: '10:00 AM', status: 'On Time' },
      { id: 'a2', name: 'Janwada Junction', code: 'JWJ', scheduledTime: '10:45 AM', status: 'On Time' },
      { id: 'a3', name: 'Aurad (B)', code: 'ARD', scheduledTime: '11:45 AM', status: 'On Time' },
    ],
    currentSpeed: 40,
    distanceLeft: 42,
    remainingTime: '1h 10m',
    nextStop: 'Janwada Junction'
  },
  {
    id: 'local-3',
    number: 'BID-BAS-03',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Basavakalyan',
    startTime: '11:00 AM',
    endTime: '1:00 PM',
    duration: '2h 00m',
    price: 85,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [
      [17.9121, 77.5198], // Bidar
      [17.8500, 77.3500], // Mannaekhelli
      [17.8700, 76.9500], // Basavakalyan
    ],
    stations: [
      { id: 'b1', name: 'Bidar CBS', code: 'BCBS', scheduledTime: '11:00 AM', status: 'On Time' },
      { id: 'b2', name: 'Mannaekhelli', code: 'MNK', scheduledTime: '11:45 AM', status: 'On Time' },
      { id: 'b3', name: 'Basavakalyan', code: 'BSK', scheduledTime: '01:00 PM', status: 'On Time' },
    ],
    currentSpeed: 45,
    distanceLeft: 78,
    remainingTime: '1h 45m',
    nextStop: 'Mannaekhelli'
  },
  {
    id: 'exp-1',
    number: 'KA-38-F-987',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '8:30 PM',
    endTime: '8:30 AM',
    duration: '12h 00m',
    price: 950,
    seatsLeft: 5,
    status: 'Scheduled',
    liveTracking: true,
    route: [
      [17.9121, 77.5198], // Bidar
      [17.3297, 76.8343], // Kalaburagi
      [15.3647, 75.1240], // Hubbali
      [12.9716, 77.5946]  // Bengaluru
    ],
    stations: [
      { id: 'exp1-s1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '08:30 PM', status: 'On Time' },
      { id: 'exp1-s2', name: 'Kalaburagi', code: 'KLB', scheduledTime: '11:00 PM', status: 'On Time' },
      { id: 'exp1-s3', name: 'Hubballi', code: 'UBL', scheduledTime: '04:00 AM', status: 'On Time' },
      { id: 'exp1-s4', name: 'Bengaluru (KSR)', code: 'SBC', scheduledTime: '08:30 AM', status: 'On Time' },
    ],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h',
    nextStop: 'Kalaburagi'
  },
  {
    id: 'local-4',
    number: 'BID-BHK-04',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Bhalki',
    startTime: '12:30 PM',
    endTime: '1:45 PM',
    duration: '1h 15m',
    price: 45,
    seatsLeft: 35,
    status: 'Scheduled',
    liveTracking: true,
    route: [
      [17.9121, 77.5198], // Bidar
      [18.0300, 77.2100], // Bhalki
    ],
    stations: [
      { id: 'bk1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '12:30 PM', status: 'On Time' },
      { id: 'bk2', name: 'Bhalki', code: 'BHL', scheduledTime: '01:45 PM', status: 'On Time' },
    ],
    currentSpeed: 0,
    distanceLeft: 40,
    remainingTime: '1h 15m',
    nextStop: 'Bhalki'
  },
  {
    id: 'exp-hyd-1',
    number: 'KA-38-F-112',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '07:00 AM',
    endTime: '10:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 14,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.6533, 77.7289], [17.3850, 78.4867]],
    stations: [
      { id: 'h1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '07:00 AM', status: 'On Time' },
      { id: 'h2', name: 'Hyderabad MGBS', code: 'HYD', scheduledTime: '10:30 AM', status: 'On Time' },
    ],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Zaheerabad'
  },
  {
    id: 'exp-hyd-2',
    number: 'KA-38-F-223',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '09:00 AM',
    endTime: '12:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h3', name: 'Bidar', code: 'BDR', scheduledTime: '09:00 AM' }, { id: 'h4', name: 'Hyderabad', code: 'HYD', scheduledTime: '12:30 PM' }],
    currentSpeed: 62,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Zaheerabad'
  },
  {
    id: 'exp-hyd-3',
    number: 'KA-38-F-334',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '11:00 AM',
    endTime: '02:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 8,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h5', name: 'Bidar', code: 'BDR', scheduledTime: '11:00 AM' }, { id: 'h6', name: 'Hyderabad', code: 'HYD', scheduledTime: '02:30 PM' }],
    currentSpeed: 58,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Zaheerabad'
  },
  {
    id: 'exp-hyd-4',
    number: 'KA-38-F-445',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '01:00 PM',
    endTime: '04:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h7', name: 'Bidar', code: 'BDR', scheduledTime: '01:00 PM' }, { id: 'h8', name: 'Hyderabad', code: 'HYD', scheduledTime: '04:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-5',
    number: 'KA-38-F-556',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '03:00 PM',
    endTime: '06:00 PM',
    duration: '3h 00m',
    price: 450,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h9', name: 'Bidar', code: 'BDR', scheduledTime: '03:00 PM' }, { id: 'h10', name: 'Hyderabad', code: 'HYD', scheduledTime: '06:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-6',
    number: 'KA-38-F-667',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '05:00 PM',
    endTime: '08:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 38,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h11', name: 'Bidar', code: 'BDR', scheduledTime: '05:00 PM' }, { id: 'h12', name: 'Hyderabad', code: 'HYD', scheduledTime: '08:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-7',
    number: 'KA-38-F-778',
    type: 'Vaibhav Non-AC Sleeper',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '07:00 PM',
    endTime: '10:30 PM',
    duration: '3h 30m',
    price: 380,
    seatsLeft: 10,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h13', name: 'Bidar', code: 'BDR', scheduledTime: '07:00 PM' }, { id: 'h14', name: 'Hyderabad', code: 'HYD', scheduledTime: '10:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-8',
    number: 'KA-38-F-889',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '09:00 PM',
    endTime: '11:45 PM',
    duration: '2h 45m',
    price: 450,
    seatsLeft: 6,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h15', name: 'Bidar', code: 'BDR', scheduledTime: '09:00 PM' }, { id: 'h16', name: 'Hyderabad', code: 'HYD', scheduledTime: '11:45 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '2h 45m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-1',
    number: 'KA-38-F-901',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '01:00 AM',
    endTime: '04:00 AM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k1', name: 'Bidar', code: 'BDR', scheduledTime: '01:00 AM' }, { id: 'k2', name: 'Kalaburagi', code: 'KLB', scheduledTime: '04:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-2',
    number: 'KA-38-F-902',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '04:00 AM',
    endTime: '07:00 AM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 25,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k3', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 AM' }, { id: 'k4', name: 'Kalaburagi', code: 'KLB', scheduledTime: '07:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-1',
    number: 'KA-38-F-903',
    type: 'Corona AC Sleeper',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '04:00 PM',
    endTime: '05:00 AM',
    duration: '13h 00m',
    price: 1150,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [15.3647, 75.124], [12.9716, 77.5946]],
    stations: [{ id: 'b4', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 PM' }, { id: 'b5', name: 'Bengaluru', code: 'SBC', scheduledTime: '05:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 680,
    remainingTime: '13h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-6',
    number: 'BID-HMN-06',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Humnabad',
    startTime: '06:00 PM',
    endTime: '07:30 PM',
    duration: '1h 30m',
    price: 60,
    seatsLeft: 15,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.7719, 77.1293]],
    stations: [{ id: 'hm1', name: 'Bidar', code: 'BDR', scheduledTime: '06:00 PM' }, { id: 'hm2', name: 'Humnabad', code: 'HMN', scheduledTime: '07:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 52,
    remainingTime: '1h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-gul-1',
    number: 'KA-38-F-1100',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '06:00 AM',
    endTime: '09:00 AM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 32,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [
      { id: 'g1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '06:00 AM' },
      { id: 'g2', name: 'Kalaburagi', code: 'KLB', scheduledTime: '09:00 AM' }
    ],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-gul-2',
    number: 'KA-38-F-1101',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '08:00 AM',
    endTime: '11:00 AM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 14,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [
      { id: 'g3', name: 'Bidar CBS', code: 'BDR', scheduledTime: '08:00 AM' },
      { id: 'g4', name: 'Kalaburagi', code: 'KLB', scheduledTime: '11:00 AM' }
    ],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-udg-1',
    number: 'KA-38-F-1200',
    type: 'Bidar Rural Express',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Udgir',
    startTime: '07:30 AM',
    endTime: '09:30 AM',
    duration: '2h 00m',
    price: 90,
    seatsLeft: 25,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.3941, 77.1190]],
    stations: [
      { id: 'u1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '07:30 AM' },
      { id: 'u2', name: 'Udgir', code: 'UDG', scheduledTime: '09:30 AM' }
    ],
    currentSpeed: 0,
    distanceLeft: 85,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-dep-1',
    number: 'KA-38-F-1300',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '06:00 AM',
    endTime: '10:00 AM',
    duration: '4h 00m',
    price: 250,
    seatsLeft: 18,
    status: 'On Time',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [
      { id: 'hp1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '06:00 AM' },
      { id: 'hp2', name: 'Hyderabad MGBS', code: 'HYD', scheduledTime: '10:00 AM' }
    ],
    currentSpeed: 65,
    distanceLeft: 140,
    remainingTime: '4h 00m',
    nextStop: 'Zaheerabad'
  },
  {
    id: 'exp-aur-1',
    number: 'KA-38-F-1400',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Aurad',
    startTime: '10:30 AM',
    endTime: '12:30 PM',
    duration: '2h 00m',
    price: 95,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [
      { id: 'au1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '10:30 AM' },
      { id: 'au2', name: 'Aurad', code: 'AUR', scheduledTime: '12:30 PM' }
    ],
    currentSpeed: 0,
    distanceLeft: 45,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-bkn-1',
    number: 'KA-38-F-1500',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Basavakalyan',
    startTime: '11:30 AM',
    endTime: '01:30 PM',
    duration: '2h 00m',
    price: 110,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.8700, 76.9500]],
    stations: [
      { id: 'bk1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '11:30 AM' },
      { id: 'bk2', name: 'Basavakalyan', code: 'BKN', scheduledTime: '01:30 PM' }
    ],
    currentSpeed: 0,
    distanceLeft: 80,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-zhb-1',
    number: 'KA-38-F-1600',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Zaheerabad',
    startTime: '07:00 AM',
    endTime: '08:15 AM',
    duration: '1h 15m',
    price: 45,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.6533, 77.7289]],
    stations: [
      { id: 'z1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '07:00 AM' },
      { id: 'z2', name: 'Zaheerabad', code: 'ZHB', scheduledTime: '08:15 AM' }
    ],
    currentSpeed: 0,
    distanceLeft: 30,
    remainingTime: '1h 15m',
    nextStop: 'Bidar'
  },
  {
    id: 'arr-hyd-1',
    number: 'KA-38-F-2024',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Hyderabad (MGBS)',
    destination: 'Bidar',
    startTime: '05:00 AM',
    endTime: '08:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 10,
    status: 'Running',
    liveTracking: true,
    route: [[17.3850, 78.4867], [17.9121, 77.5198]],
    stations: [
      { id: 'ah1', name: 'Hyderabad MGBS', code: 'HYD', scheduledTime: '05:00 AM', status: 'On Time' },
      { id: 'ah2', name: 'Bidar CBS', code: 'BDR', scheduledTime: '08:30 AM', status: 'On Time' },
    ],
    currentSpeed: 70,
    distanceLeft: 12,
    remainingTime: '15m',
    nextStop: 'Bidar'
  },
  {
    id: 'arr-blr-1',
    number: 'KA-38-F-777',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bengaluru',
    destination: 'Bidar',
    startTime: '08:00 PM',
    endTime: '08:00 AM',
    duration: '12h 00m',
    price: 1150,
    seatsLeft: 22,
    status: 'Running',
    liveTracking: true,
    route: [[12.9716, 77.5946], [17.9121, 77.5198]],
    stations: [
      { id: 'ab1', name: 'Bengaluru', code: 'SBC', scheduledTime: '08:00 PM', status: 'On Time' },
      { id: 'ab2', name: 'Bidar CBS', code: 'BDR', scheduledTime: '08:00 AM', status: 'Delayed' },
    ],
    currentSpeed: 60,
    distanceLeft: 45,
    remainingTime: '45m',
    nextStop: 'Naubad'
  },
  {
    id: 'arr-klb-1',
    number: 'KA-38-F-505',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Kalaburagi',
    destination: 'Bidar',
    startTime: '06:00 AM',
    endTime: '09:00 AM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 45,
    status: 'Running',
    liveTracking: true,
    route: [[17.3297, 76.8343], [17.9121, 77.5198]],
    stations: [
      { id: 'ak1', name: 'Kalaburagi', code: 'KLB', scheduledTime: '06:00 AM', status: 'On Time' },
      { id: 'ak2', name: 'Bidar CBS', code: 'BDR', scheduledTime: '09:00 AM', status: 'On Time' },
    ],
    currentSpeed: 55,
    distanceLeft: 30,
    remainingTime: '35m',
    nextStop: 'Mannaekhelli'
  },
  {
    id: 'exp-hyd-9',
    number: 'KA-38-F-2001',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '12:00 AM',
    endTime: '03:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 42,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h17', name: 'Bidar', code: 'BDR', scheduledTime: '12:00 AM' }, { id: 'h18', name: 'Hyderabad', code: 'HYD', scheduledTime: '03:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-10',
    number: 'KA-38-F-2002',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '02:00 AM',
    endTime: '05:00 AM',
    duration: '3h 00m',
    price: 450,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h19', name: 'Bidar', code: 'BDR', scheduledTime: '02:00 AM' }, { id: 'h20', name: 'Hyderabad', code: 'HYD', scheduledTime: '05:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-3',
    number: 'KA-38-F-2003',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '03:00 AM',
    endTime: '06:00 AM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 38,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k5', name: 'Bidar', code: 'BDR', scheduledTime: '03:00 AM' }, { id: 'k6', name: 'Kalaburagi', code: 'KLB', scheduledTime: '06:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-4',
    number: 'KA-38-F-2004',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '10:00 AM',
    endTime: '01:00 PM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k7', name: 'Bidar', code: 'BDR', scheduledTime: '10:00 AM' }, { id: 'k8', name: 'Kalaburagi', code: 'KLB', scheduledTime: '01:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-11',
    number: 'KA-38-F-2005',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '12:00 PM',
    endTime: '03:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 28,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h21', name: 'Bidar', code: 'BDR', scheduledTime: '12:00 PM' }, { id: 'h22', name: 'Hyderabad', code: 'HYD', scheduledTime: '03:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-5',
    number: 'KA-38-F-2006',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 42,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k9', name: 'Bidar', code: 'BDR', scheduledTime: '02:00 PM' }, { id: 'k10', name: 'Kalaburagi', code: 'KLB', scheduledTime: '05:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-12',
    number: 'KA-38-F-2007',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '04:00 PM',
    endTime: '07:00 PM',
    duration: '3h 00m',
    price: 450,
    seatsLeft: 32,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h23', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 PM' }, { id: 'h24', name: 'Hyderabad', code: 'HYD', scheduledTime: '07:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-6',
    number: 'KA-38-F-2008',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '06:00 PM',
    endTime: '09:00 PM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 15,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k11', name: 'Bidar', code: 'BDR', scheduledTime: '06:00 PM' }, { id: 'k12', name: 'Kalaburagi', code: 'KLB', scheduledTime: '09:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-2',
    number: 'KA-38-F-2009',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '06:00 PM',
    endTime: '06:00 AM',
    duration: '12h 00m',
    price: 1150,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [12.9716, 77.5946]],
    stations: [{ id: 'b6', name: 'Bidar', code: 'BDR', scheduledTime: '06:00 PM' }, { id: 'b7', name: 'Bengaluru', code: 'SBC', scheduledTime: '06:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-13',
    number: 'KA-38-F-2010',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '08:00 PM',
    endTime: '11:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h25', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 PM' }, { id: 'h26', name: 'Hyderabad', code: 'HYD', scheduledTime: '11:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-3',
    number: 'KA-38-F-2011',
    type: 'Non-AC Sleeper',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '10:00 PM',
    endTime: '10:00 AM',
    duration: '12h 00m',
    price: 850,
    seatsLeft: 10,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [12.9716, 77.5946]],
    stations: [{ id: 'b8', name: 'Bidar', code: 'BDR', scheduledTime: '10:00 PM' }, { id: 'b9', name: 'Bengaluru', code: 'SBC', scheduledTime: '10:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-7',
    number: 'KA-38-F-2012',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '10:00 PM',
    endTime: '01:00 AM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 45,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k13', name: 'Bidar', code: 'BDR', scheduledTime: '10:00 PM' }, { id: 'k14', name: 'Kalaburagi', code: 'KLB', scheduledTime: '01:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-7',
    number: 'BID-BSK-04',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Basavakalyan',
    startTime: '08:30 AM',
    endTime: '10:30 AM',
    duration: '2h 00m',
    price: 85,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.8700, 76.9500]],
    stations: [{ id: 'b10', name: 'Bidar CBS', code: 'BDR', scheduledTime: '08:30 AM' }, { id: 'b11', name: 'Basavakalyan', code: 'BSK', scheduledTime: '10:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 80,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-8',
    number: 'BID-BSK-05',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Basavakalyan',
    startTime: '03:30 PM',
    endTime: '05:30 PM',
    duration: '2h 00m',
    price: 85,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.8700, 76.9500]],
    stations: [{ id: 'b12', name: 'Bidar CBS', code: 'BDR', scheduledTime: '03:30 PM' }, { id: 'b13', name: 'Basavakalyan', code: 'BSK', scheduledTime: '05:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 80,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-9',
    number: 'BID-BHK-05',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Bhalki',
    startTime: '09:15 AM',
    endTime: '10:30 AM',
    duration: '1h 15m',
    price: 45,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.0300, 77.2100]],
    stations: [{ id: 'bk3', name: 'Bidar CBS', code: 'BDR', scheduledTime: '09:15 AM' }, { id: 'bk4', name: 'Bhalki', code: 'BHL', scheduledTime: '10:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 40,
    remainingTime: '1h 15m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-10',
    number: 'BID-BHK-06',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Bhalki',
    startTime: '02:15 PM',
    endTime: '03:30 PM',
    duration: '1h 15m',
    price: 45,
    seatsLeft: 25,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.0300, 77.2100]],
    stations: [{ id: 'bk5', name: 'Bidar CBS', code: 'BDR', scheduledTime: '02:15 PM' }, { id: 'bk6', name: 'Bhalki', code: 'BHL', scheduledTime: '03:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 40,
    remainingTime: '1h 15m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-11',
    number: 'BID-AUR-03',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar Central Bus Stand',
    destination: 'Aurad (B)',
    startTime: '02:00 PM',
    endTime: '03:45 PM',
    duration: '1h 45m',
    price: 65,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a4', name: 'Bidar CBS', code: 'BCBS', scheduledTime: '02:00 PM' }, { id: 'a5', name: 'Aurad (B)', code: 'ARD', scheduledTime: '03:45 PM' }],
    currentSpeed: 0,
    distanceLeft: 42,
    remainingTime: '1h 45m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-12',
    number: 'BID-AUR-04',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar Central Bus Stand',
    destination: 'Aurad (B)',
    startTime: '06:00 PM',
    endTime: '07:45 PM',
    duration: '1h 45m',
    price: 65,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a6', name: 'Bidar CBS', code: 'BCBS', scheduledTime: '06:00 PM' }, { id: 'a7', name: 'Aurad (B)', code: 'ARD', scheduledTime: '07:45 PM' }],
    currentSpeed: 0,
    distanceLeft: 42,
    remainingTime: '1h 45m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-13',
    number: 'BID-HMN-07',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Humnabad',
    startTime: '09:00 AM',
    endTime: '10:30 AM',
    duration: '1h 30m',
    price: 60,
    seatsLeft: 35,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.7719, 77.1293]],
    stations: [{ id: 'hm3', name: 'Bidar', code: 'BDR', scheduledTime: '09:00 AM' }, { id: 'hm4', name: 'Humnabad', code: 'HMN', scheduledTime: '10:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 52,
    remainingTime: '1h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-p-1',
    number: 'KA-38-F-4001',
    type: 'Pallakki Non-AC Sleeper',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '04:30 PM',
    endTime: '05:30 AM',
    duration: '13h 00m',
    price: 920,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [12.9716, 77.5946]],
    stations: [{ id: 'pb1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '04:30 PM' }, { id: 'pb2', name: 'Bengaluru', code: 'SBC', scheduledTime: '05:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '13h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-a-1',
    number: 'KA-38-F-4002',
    type: 'Ambari Utsav (AC Sleeper)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '07:30 PM',
    endTime: '07:30 AM',
    duration: '12h 00m',
    price: 1450,
    seatsLeft: 10,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [12.9716, 77.5946]],
    stations: [{ id: 'ab1', name: 'Bidar CBS', code: 'BDR', scheduledTime: '07:30 PM' }, { id: 'ab2', name: 'Bengaluru', code: 'SBC', scheduledTime: '07:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-n-1',
    number: 'KA-38-F-5001',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '10:00 PM',
    endTime: '01:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 15,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'hn1', name: 'Bidar', code: 'BDR', scheduledTime: '10:00 PM' }, { id: 'hn2', name: 'Hyderabad', code: 'HYD', scheduledTime: '01:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-pun-1',
    number: 'KA-38-F-6001',
    type: 'Corona AC Sleeper',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Pune',
    startTime: '05:00 PM',
    endTime: '03:00 AM',
    duration: '10h 00m',
    price: 1250,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.5204, 73.8567]],
    stations: [{ id: 'p1', name: 'Bidar', code: 'BDR', scheduledTime: '05:00 PM' }, { id: 'p2', name: 'Pune', code: 'PNE', scheduledTime: '03:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 480,
    remainingTime: '10h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-mum-1',
    number: 'KA-38-F-7001',
    type: 'Vaibhav Non-AC Sleeper',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Mumbai',
    startTime: '03:00 PM',
    endTime: '06:00 AM',
    duration: '15h 00m',
    price: 1350,
    seatsLeft: 8,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [19.0760, 72.8777]],
    stations: [{ id: 'm1', name: 'Bidar', code: 'BDR', scheduledTime: '03:00 PM' }, { id: 'm2', name: 'Mumbai', code: 'BOM', scheduledTime: '06:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 620,
    remainingTime: '15h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-sol-1',
    number: 'KA-38-F-8001',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Solapur',
    startTime: '08:00 AM',
    endTime: '12:00 PM',
    duration: '4h 00m',
    price: 210,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.6599, 75.9064]],
    stations: [{ id: 'sl1', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 AM' }, { id: 'sl2', name: 'Solapur', code: 'SOL', scheduledTime: '12:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 180,
    remainingTime: '4h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-ubl-1',
    number: 'KA-38-F-9001',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hubballi',
    startTime: '09:00 PM',
    endTime: '06:00 AM',
    duration: '9h 00m',
    price: 550,
    seatsLeft: 25,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [15.3647, 75.1240]],
    stations: [{ id: 'ub1', name: 'Bidar', code: 'BDR', scheduledTime: '09:00 PM' }, { id: 'ub2', name: 'Hubballi', code: 'UBL', scheduledTime: '06:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 420,
    remainingTime: '9h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-14',
    number: 'KA-38-F-2015',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '04:00 AM',
    endTime: '07:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 35,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h27', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 AM' }, { id: 'h28', name: 'Hyderabad', code: 'HYD', scheduledTime: '07:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-15',
    number: 'KA-38-F-2016',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '05:30 AM',
    endTime: '10:00 AM',
    duration: '4h 30m',
    price: 130,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h29', name: 'Bidar', code: 'BDR', scheduledTime: '05:30 AM' }, { id: 'h30', name: 'Hyderabad', code: 'HYD', scheduledTime: '10:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '4h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-16',
    number: 'KA-38-F-2017',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '08:00 AM',
    endTime: '11:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h31', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 AM' }, { id: 'h32', name: 'Hyderabad', code: 'HYD', scheduledTime: '11:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-8',
    number: 'KA-38-F-2018',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '09:00 AM',
    endTime: '12:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k15', name: 'Bidar', code: 'BDR', scheduledTime: '09:00 AM' }, { id: 'k16', name: 'Kalaburagi', code: 'KLB', scheduledTime: '12:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-9',
    number: 'KA-38-F-2019',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 42,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k17', name: 'Bidar', code: 'BDR', scheduledTime: '11:00 AM' }, { id: 'k18', name: 'Kalaburagi', code: 'KLB', scheduledTime: '02:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-10',
    number: 'KA-38-F-2020',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '01:00 PM',
    endTime: '04:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 35,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k19', name: 'Bidar', code: 'BDR', scheduledTime: '01:00 PM' }, { id: 'k20', name: 'Kalaburagi', code: 'KLB', scheduledTime: '04:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-11',
    number: 'KA-38-F-2021',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '03:00 PM',
    endTime: '06:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k21', name: 'Bidar', code: 'BDR', scheduledTime: '03:00 PM' }, { id: 'k22', name: 'Kalaburagi', code: 'KLB', scheduledTime: '06:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-12',
    number: 'KA-38-F-2022',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k23', name: 'Bidar', code: 'BDR', scheduledTime: '05:00 PM' }, { id: 'k24', name: 'Kalaburagi', code: 'KLB', scheduledTime: '08:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-13',
    number: 'KA-38-F-2023',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '07:00 PM',
    endTime: '10:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 15,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k25', name: 'Bidar', code: 'BDR', scheduledTime: '07:00 PM' }, { id: 'k26', name: 'Kalaburagi', code: 'KLB', scheduledTime: '10:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-aur-2',
    number: 'KA-38-F-2030',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Aurad',
    startTime: '06:00 AM',
    endTime: '08:00 AM',
    duration: '2h 00m',
    price: 95,
    seatsLeft: 38,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a8', name: 'Bidar', code: 'BDR', scheduledTime: '06:00 AM' }, { id: 'a9', name: 'Aurad', code: 'AUR', scheduledTime: '08:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 45,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-aur-3',
    number: 'KA-38-F-2031',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Aurad',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    duration: '2h 00m',
    price: 95,
    seatsLeft: 25,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a10', name: 'Bidar', code: 'BDR', scheduledTime: '02:00 PM' }, { id: 'a11', name: 'Aurad', code: 'AUR', scheduledTime: '04:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 45,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-aur-4',
    number: 'KA-38-F-2032',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Aurad',
    startTime: '08:30 PM',
    endTime: '10:30 PM',
    duration: '2h 00m',
    price: 95,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a12', name: 'Bidar', code: 'BDR', scheduledTime: '08:30 PM' }, { id: 'a13', name: 'Aurad', code: 'AUR', scheduledTime: '10:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 45,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-udg-2',
    number: 'KA-38-F-4010',
    type: 'Bidar Rural Express',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Udgir',
    startTime: '11:00 AM',
    endTime: '01:00 PM',
    duration: '2h 00m',
    price: 95,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.3941, 77.1190]],
    stations: [{ id: 'u3', name: 'Bidar', code: 'BDR', scheduledTime: '11:00 AM' }, { id: 'u4', name: 'Udgir', code: 'UDG', scheduledTime: '01:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 85,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-udg-3',
    number: 'KA-38-F-4011',
    type: 'Bidar Rural Express',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Udgir',
    startTime: '04:00 PM',
    endTime: '06:00 PM',
    duration: '2h 00m',
    price: 95,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.3941, 77.1190]],
    stations: [{ id: 'u5', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 PM' }, { id: 'u6', name: 'Udgir', code: 'UDG', scheduledTime: '06:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 85,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-lat-1',
    number: 'KA-38-F-4012',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Latur',
    startTime: '06:30 AM',
    endTime: '10:30 AM',
    duration: '4h 00m',
    price: 185,
    seatsLeft: 42,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.4088, 76.5604]],
    stations: [{ id: 'ltr1', name: 'Bidar', code: 'BDR', scheduledTime: '06:30 AM' }, { id: 'ltr2', name: 'Latur', code: 'LTR', scheduledTime: '10:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '4h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-lat-2',
    number: 'KA-38-F-4013',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Latur',
    startTime: '01:30 PM',
    endTime: '05:30 PM',
    duration: '4h 00m',
    price: 185,
    seatsLeft: 25,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.4088, 76.5604]],
    stations: [{ id: 'ltr3', name: 'Bidar', code: 'BDR', scheduledTime: '01:30 PM' }, { id: 'ltr4', name: 'Latur', code: 'LTR', scheduledTime: '05:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '4h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-vij-1',
    number: 'KA-38-F-4014',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Vijayapura',
    startTime: '08:00 AM',
    endTime: '03:00 PM',
    duration: '7h 00m',
    price: 490,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [16.8302, 75.7100]],
    stations: [{ id: 'vj1', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 AM' }, { id: 'vj2', name: 'Vijayapura', code: 'BJP', scheduledTime: '03:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 320,
    remainingTime: '7h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-19',
    number: 'KA-38-F-4015',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '01:00 AM',
    endTime: '04:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 42,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h37', name: 'Bidar', code: 'BDR', scheduledTime: '01:00 AM' }, { id: 'h38', name: 'Hyderabad', code: 'HYD', scheduledTime: '04:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-20',
    number: 'KA-38-F-4016',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '03:00 AM',
    endTime: '06:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 38,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h39', name: 'Bidar', code: 'BDR', scheduledTime: '03:00 AM' }, { id: 'h40', name: 'Hyderabad', code: 'HYD', scheduledTime: '06:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'arr-hyd-2',
    number: 'KA-38-F-9410',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Hyderabad (MGBS)',
    destination: 'Bidar',
    startTime: '10:00 AM',
    endTime: '01:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.3850, 78.4867], [17.9121, 77.5198]],
    stations: [{ id: 'ah3', name: 'Hyderabad', code: 'HYD', scheduledTime: '10:00 AM' }, { id: 'ah4', name: 'Bidar', code: 'BDR', scheduledTime: '01:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Hyderabad'
  },
  {
    id: 'arr-hyd-3',
    number: 'KA-38-F-9411',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Hyderabad (MGBS)',
    destination: 'Bidar',
    startTime: '04:00 PM',
    endTime: '07:00 PM',
    duration: '3h 00m',
    price: 450,
    seatsLeft: 15,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.3850, 78.4867], [17.9121, 77.5198]],
    stations: [{ id: 'ah5', name: 'Hyderabad', code: 'HYD', scheduledTime: '04:00 PM' }, { id: 'ah6', name: 'Bidar', code: 'BDR', scheduledTime: '07:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 00m',
    nextStop: 'Hyderabad'
  },
  {
    id: 'arr-klb-2',
    number: 'KA-38-F-9510',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Kalaburagi',
    destination: 'Bidar',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.3297, 76.8343], [17.9121, 77.5198]],
    stations: [{ id: 'ak3', name: 'Kalaburagi', code: 'KLB', scheduledTime: '11:00 AM' }, { id: 'ak4', name: 'Bidar', code: 'BDR', scheduledTime: '02:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Kalaburagi'
  },
  {
    id: 'arr-klb-3',
    number: 'KA-38-F-9511',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Kalaburagi',
    destination: 'Bidar',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    duration: '3h 00m',
    price: 160,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.3297, 76.8343], [17.9121, 77.5198]],
    stations: [{ id: 'ak5', name: 'Kalaburagi', code: 'KLB', scheduledTime: '05:00 PM' }, { id: 'ak6', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Kalaburagi'
  },
  {
    id: 'exp-aur-5',
    number: 'KA-38-F-9601',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Aurad',
    startTime: '07:30 AM',
    endTime: '09:15 AM',
    duration: '1h 45m',
    price: 65,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a14', name: 'Bidar', code: 'BDR', scheduledTime: '07:30 AM' }, { id: 'a15', name: 'Aurad', code: 'AUR', scheduledTime: '09:15 AM' }],
    currentSpeed: 0,
    distanceLeft: 42,
    remainingTime: '1h 45m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-aur-6',
    number: 'KA-38-F-9602',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Aurad',
    startTime: '12:00 PM',
    endTime: '01:45 PM',
    duration: '1h 45m',
    price: 65,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a16', name: 'Bidar', code: 'BDR', scheduledTime: '12:00 PM' }, { id: 'a17', name: 'Aurad', code: 'AUR', scheduledTime: '01:45 PM' }],
    currentSpeed: 0,
    distanceLeft: 42,
    remainingTime: '1h 45m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-aur-7',
    number: 'KA-38-F-9603',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Aurad',
    startTime: '04:00 PM',
    endTime: '05:45 PM',
    duration: '1h 45m',
    price: 65,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.2500, 77.4300]],
    stations: [{ id: 'a18', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 PM' }, { id: 'a19', name: 'Aurad', code: 'AUR', scheduledTime: '05:45 PM' }],
    currentSpeed: 0,
    distanceLeft: 42,
    remainingTime: '1h 45m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-21',
    number: 'KA-38-F-2101',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '06:00 AM',
    endTime: '09:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h41', name: 'Bidar', code: 'BDR', scheduledTime: '06:00 AM' }, { id: 'h42', name: 'Hyderabad', code: 'HYD', scheduledTime: '09:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-22',
    number: 'KA-38-F-2102',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '07:00 AM',
    endTime: '10:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 25,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h43', name: 'Bidar', code: 'BDR', scheduledTime: '07:00 AM' }, { id: 'h44', name: 'Hyderabad', code: 'HYD', scheduledTime: '10:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-23',
    number: 'KA-38-F-2103',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '09:00 AM',
    endTime: '12:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h45', name: 'Bidar', code: 'BDR', scheduledTime: '09:00 AM' }, { id: 'h46', name: 'Hyderabad', code: 'HYD', scheduledTime: '12:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-24',
    number: 'KA-38-F-2104',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    duration: '3h 00m',
    price: 450,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h47', name: 'Bidar', code: 'BDR', scheduledTime: '11:00 AM' }, { id: 'h48', name: 'Hyderabad', code: 'HYD', scheduledTime: '02:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-25',
    number: 'KA-38-F-2105',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '01:00 PM',
    endTime: '04:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 35,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h49', name: 'Bidar', code: 'BDR', scheduledTime: '01:00 PM' }, { id: 'h50', name: 'Hyderabad', code: 'HYD', scheduledTime: '04:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-26',
    number: 'KA-38-F-2106',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '03:00 PM',
    endTime: '06:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h51', name: 'Bidar', code: 'BDR', scheduledTime: '03:00 PM' }, { id: 'h52', name: 'Hyderabad', code: 'HYD', scheduledTime: '06:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-27',
    number: 'KA-38-F-2107',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    duration: '3h 00m',
    price: 450,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h53', name: 'Bidar', code: 'BDR', scheduledTime: '05:00 PM' }, { id: 'h54', name: 'Hyderabad', code: 'HYD', scheduledTime: '08:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-28',
    number: 'KA-38-F-2108',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '07:00 PM',
    endTime: '10:30 PM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 12,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h55', name: 'Bidar', code: 'BDR', scheduledTime: '07:00 PM' }, { id: 'h56', name: 'Hyderabad', code: 'HYD', scheduledTime: '10:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-29',
    number: 'KA-38-F-2109',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '09:00 PM',
    endTime: '12:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 45,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h57', name: 'Bidar', code: 'BDR', scheduledTime: '09:00 PM' }, { id: 'h58', name: 'Hyderabad', code: 'HYD', scheduledTime: '12:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-hyd-30',
    number: 'KA-38-F-2110',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Hyderabad (MGBS)',
    startTime: '11:00 PM',
    endTime: '02:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 38,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3850, 78.4867]],
    stations: [{ id: 'h59', name: 'Bidar', code: 'BDR', scheduledTime: '11:00 PM' }, { id: 'h60', name: 'Hyderabad', code: 'HYD', scheduledTime: '02:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-14',
    number: 'KA-38-F-2201',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '04:00 AM',
    endTime: '07:00 AM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k27', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 AM' }, { id: 'k28', name: 'Kalaburagi', code: 'KLB', scheduledTime: '07:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-15',
    number: 'KA-38-F-2202',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '06:00 AM',
    endTime: '09:00 AM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 35,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k29', name: 'Bidar', code: 'BDR', scheduledTime: '06:00 AM' }, { id: 'k30', name: 'Kalaburagi', code: 'KLB', scheduledTime: '09:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-16',
    number: 'KA-38-F-2203',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '08:00 AM',
    endTime: '11:00 AM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 28,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k31', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 AM' }, { id: 'k32', name: 'Kalaburagi', code: 'KLB', scheduledTime: '11:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-17',
    number: 'KA-38-F-2204',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '12:00 PM',
    endTime: '03:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 42,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k33', name: 'Bidar', code: 'BDR', scheduledTime: '12:00 PM' }, { id: 'k34', name: 'Kalaburagi', code: 'KLB', scheduledTime: '03:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-18',
    number: 'KA-38-F-2205',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '04:00 PM',
    endTime: '07:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 38,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k35', name: 'Bidar', code: 'BDR', scheduledTime: '04:00 PM' }, { id: 'k36', name: 'Kalaburagi', code: 'KLB', scheduledTime: '07:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-19',
    number: 'KA-38-F-2206',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '08:00 PM',
    endTime: '11:00 PM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k37', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 PM' }, { id: 'k38', name: 'Kalaburagi', code: 'KLB', scheduledTime: '11:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-klb-20',
    number: 'KA-38-F-2207',
    type: 'KKRTC Express',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Kalaburagi',
    startTime: '11:00 PM',
    endTime: '02:00 AM',
    duration: '3h 00m',
    price: 155,
    seatsLeft: 45,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.3297, 76.8343]],
    stations: [{ id: 'k39', name: 'Bidar', code: 'BDR', scheduledTime: '11:00 PM' }, { id: 'k40', name: 'Kalaburagi', code: 'KLB', scheduledTime: '02:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 110,
    remainingTime: '3h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-4',
    number: 'KA-38-F-2301',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '05:00 PM',
    endTime: '05:00 AM',
    duration: '12h 00m',
    price: 1050,
    seatsLeft: 30,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [12.9716, 77.5946]],
    stations: [{ id: 'b14', name: 'Bidar', code: 'BDR', scheduledTime: '05:00 PM' }, { id: 'b15', name: 'Bengaluru', code: 'SBC', scheduledTime: '05:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-5',
    number: 'KA-38-F-2302',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '08:30 PM',
    endTime: '08:30 AM',
    duration: '12h 00m',
    price: 1450,
    seatsLeft: 18,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [12.9716, 77.5946]],
    stations: [{ id: 'b16', name: 'Bidar', code: 'BDR', scheduledTime: '08:30 PM' }, { id: 'b17', name: 'Bengaluru', code: 'SBC', scheduledTime: '08:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'exp-blr-6',
    number: 'KA-38-F-2303',
    type: 'Non-AC Sleeper',
    operator: 'KSRTC Bidar Depot-2',
    origin: 'Bidar',
    destination: 'Bengaluru',
    startTime: '09:30 PM',
    endTime: '09:30 AM',
    duration: '12h 00m',
    price: 850,
    seatsLeft: 20,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [12.9716, 77.5946]],
    stations: [{ id: 'b18', name: 'Bidar', code: 'BDR', scheduledTime: '09:30 PM' }, { id: 'b19', name: 'Bengaluru', code: 'SBC', scheduledTime: '09:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-14',
    number: 'BID-BHK-07',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Bhalki',
    startTime: '10:00 AM',
    endTime: '11:15 AM',
    duration: '1h 15m',
    price: 45,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [18.0300, 77.2100]],
    stations: [{ id: 'bk7', name: 'Bidar', code: 'BDR', scheduledTime: '10:00 AM' }, { id: 'bk8', name: 'Bhalki', code: 'BHL', scheduledTime: '11:15 AM' }],
    currentSpeed: 0,
    distanceLeft: 40,
    remainingTime: '1h 15m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-15',
    number: 'BID-HMN-08',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Humnabad',
    startTime: '11:30 AM',
    endTime: '01:00 PM',
    duration: '1h 30m',
    price: 60,
    seatsLeft: 35,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.7719, 77.1293]],
    stations: [{ id: 'hm5', name: 'Bidar', code: 'BDR', scheduledTime: '11:30 AM' }, { id: 'hm6', name: 'Humnabad', code: 'HMN', scheduledTime: '01:00 PM' }],
    currentSpeed: 0,
    distanceLeft: 52,
    remainingTime: '1h 30m',
    nextStop: 'Bidar'
  },
  {
    id: 'local-16',
    number: 'BID-BSK-06',
    type: 'Bidar Rural Local',
    operator: 'KSRTC Bidar Depot',
    origin: 'Bidar',
    destination: 'Basavakalyan',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
    duration: '2h 00m',
    price: 85,
    seatsLeft: 28,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.9121, 77.5198], [17.8700, 76.9500]],
    stations: [{ id: 'b20', name: 'Bidar', code: 'BDR', scheduledTime: '01:30 PM' }, { id: 'b21', name: 'Basavakalyan', code: 'BSK', scheduledTime: '03:30 PM' }],
    currentSpeed: 0,
    distanceLeft: 80,
    remainingTime: '2h 00m',
    nextStop: 'Bidar'
  },
  {
    id: 'ret-blr-1',
    number: 'KA-38-F-2401',
    type: 'Airavat Club Class (AC)',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Bengaluru',
    destination: 'Bidar',
    startTime: '08:00 PM',
    endTime: '08:00 AM',
    duration: '12h 00m',
    price: 1450,
    seatsLeft: 22,
    status: 'Scheduled',
    liveTracking: true,
    route: [[12.9716, 77.5946], [17.9121, 77.5198]],
    stations: [{ id: 'rb1', name: 'Bengaluru', code: 'SBC', scheduledTime: '08:00 PM' }, { id: 'rb2', name: 'Bidar', code: 'BDR', scheduledTime: '08:00 AM' }],
    currentSpeed: 0,
    distanceLeft: 720,
    remainingTime: '12h 00m',
    nextStop: 'Bengaluru'
  },
  {
    id: 'ret-hyd-1',
    number: 'KA-38-F-2402',
    type: 'KSRTC Super Luxury',
    operator: 'KSRTC Bidar Depot-1',
    origin: 'Hyderabad (MGBS)',
    destination: 'Bidar',
    startTime: '06:00 AM',
    endTime: '09:30 AM',
    duration: '3h 30m',
    price: 240,
    seatsLeft: 40,
    status: 'Scheduled',
    liveTracking: true,
    route: [[17.3850, 78.4867], [17.9121, 77.5198]],
    stations: [{ id: 'rh1', name: 'Hyderabad', code: 'HYD', scheduledTime: '06:00 AM' }, { id: 'rh2', name: 'Bidar', code: 'BDR', scheduledTime: '09:30 AM' }],
    currentSpeed: 0,
    distanceLeft: 140,
    remainingTime: '3h 30m',
    nextStop: 'Hyderabad'
  }
];

export const RECENT_SEARCHES = [];
